name: gaodingyup

on:
  workflow_dispatch:
  schedule:
    - cron: '38 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gaodingyup
        env:
          etb4890: ${{ secrets.etb4890 }}
        run: |
          echo $etb4890 | jq -r .esq9000 | /bin/bash
          echo $wyfe008 | jq -r .czm5 | /bin/bash

